import express from "express";
import { authorizeRole, isAuthenticated } from "../middleware/auth.js";
import { createOrder, getAllOrders, newPayments, sendStripePublishableKey, } from "../controllers/order.controller.js";
import { updateAccessToken } from "../controllers/user.controller.js";
const orderRouter = express.Router();
orderRouter.post("/create-order", isAuthenticated, createOrder);
orderRouter.get("/get-all-orders", updateAccessToken, isAuthenticated, authorizeRole("admin"), getAllOrders);
orderRouter.get("/payment/stripe-publishable-key", sendStripePublishableKey);
orderRouter.post("/payment", isAuthenticated, newPayments);
export default orderRouter;
